name: Daily Cache Cleanup

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at 00:00 UTC
  workflow_dispatch:

permissions:
  actions: write  # Required to delete caches
  contents: read

jobs:
  clear-cache:
    runs-on: ubuntu-latest

    steps:
      - name: Install GitHub CLI
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt update
          sudo apt install gh -y

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GH_PAT }}" | gh auth login --with-token

      - name: Delete all caches with prefix
        env:
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
          PREFIX: trigger-cache-
        run: |
          echo "Fetching caches for $OWNER/$REPO..."
          gh api \
            -H "Accept: application/vnd.github+json" \
            /repos/$OWNER/$REPO/actions/caches | \
            jq -c '.actions_caches[]' | while read -r cache; do
              key=$(echo "$cache" | jq -r '.key')
              id=$(echo "$cache" | jq -r '.id')
              if [[ "$key" == $PREFIX* ]]; then
                echo "Deleting cache with key: $key (ID: $id)"
                gh api --method DELETE /repos/$OWNER/$REPO/actions/caches/$id
              fi
            done
