name: Trigger Cron Runner

on:
  schedule:
    - cron: '*/5 * * * *' # every 5 minutes
  workflow_dispatch:       # also allow manual trigger

env:
  TRIGGER_URL: ${{ secrets.CRON_JOB_URL }}
  BIN_NAME: trigger.bin
  BIN_PATH: trigger-bin/trigger

jobs:
  trigger-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Cache workspace
        id: cache-workspace
        uses: actions/cache@v4
        with:
          path: |
            trigger-bin
            .workspace-state
          key: workspace-${{ runner.os }}-${{ github.ref_name }}
          restore-keys: |
            workspace-${{ runner.os }}-
      
      - name: Ensure binary folder exists
        run: mkdir -p trigger-bin

      - name: Check if trigger binary exists
        id: check_bin
        run: |
          if [[ -f "${{ env.BIN_PATH }}" ]]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Download trigger binary from private release if missing
        if: steps.check_bin.outputs.exists == 'false'
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          echo "Downloading trigger binary from GitHub release..."
          LATEST_TAG=$(curl -s -H "Authorization: token $GH_TOKEN" https://api.github.com/repos/vikshrogit/trigger/releases/latest | jq -r .tag_name)
          curl -L \
            -H "Authorization: token $GH_TOKEN" \
            -o "${{ env.BIN_PATH }}" \
            "https://github.com/vikshrogit/trigger/releases/download/${LATEST_TAG}/${{ env.BIN_NAME }}"
          chmod +x "${{ env.BIN_PATH }}"
          echo "binary_updated=true" >> $GITHUB_ENV

      - name: Run trigger binary
        run: |
          ./${{ env.BIN_PATH }} -u "${{ env.TRIGGER_URL }}"

      - name: Save updated workspace cache
        if: always()
        uses: actions/cache/save@v4
        with:
          path: |
            trigger-bin
            .workspace-state
          key: workspace-${{ runner.os }}-${{ github.ref_name }}-${{ github.run_id }}
