name: Run Health Check

on:
  schedule:
    - cron: '* * * * *'  # Every minute
  workflow_dispatch:      # Optional manual trigger for testing

jobs:
  health-check:
    runs-on: ubuntu-latest
    environment: dev   
    steps:
      - name: Trigger Dev Cronjob URL
        env:
          CRON_URL: "https://vikshro.ct.ws/health"
        run: |
          echo "Triggering $CRON_URL"
          curl -k "$CRON_URL"
