name: Trigger Cron Runner

on:
  schedule:
    - cron: '*/1 * * * *' # every 1 minute (GitHub cron is not real-time, it may run with some delay)
  workflow_dispatch:       # also allow manual trigger

env:
  TRIGGER_URL: ${{secrets.CRON_JOB_URL}}  # your input URL
  BIN_NAME: trigger.bin
  BIN_PATH: trigger-bin/trigger

jobs:
  trigger-job:
    runs-on: ubuntu-latest

    steps:
      - name: Create binary folder
        run: mkdir -p trigger-bin

      - name: Check if trigger binary exists
        id: check_bin
        run: |
          if [[ -f "${{ env.BIN_PATH }}" ]]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Download trigger binary from private release if missing
        if: steps.check_bin.outputs.exists == 'false'
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          echo "Downloading trigger binary from GitHub release..."
          LATEST_TAG=$(curl -s -H "Authorization: token $GH_TOKEN" https://api.github.com/repos/vikshrogit/trigger/releases/latest | jq -r .tag_name)
          echo "$LATEST_TAG"
          curl -L \
            -H "Authorization: token $GH_TOKEN" \
            -o "${{ env.BIN_PATH }}" \
            "https://github.com/vikshrogit/trigger/releases/download/${LATEST_TAG}/${{ env.BIN_NAME }}"
          chmod +x "${{ env.BIN_PATH }}"
          ls trigger-bin
          cat ${{ env.BIN_PATH }}

      - name: Run trigger binary with URL
        run: |
          ${{ env.BIN_PATH }} -u "${{ env.TRIGGER_URL }}"
