name: Run Health Check

on:
  schedule:
    - cron: '* * * * *'  # Every minute
  workflow_dispatch:      # Optional manual trigger for testing

jobs:
  health-check:
    runs-on: ubuntu-latest
    environment: dev   
    steps:
      - name: Trigger Dev health URL
        env:
          CRON_URL: "${{ secrets.CRON_JOB_URL}}"
        run: |
          echo "Triggering $CRON_URL"
          curl -k -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36" "$CRON_URL"
