name: Trigger Cron Runner

on:
  schedule:
    - cron: '*/1 * * * *' # every 1 minute (GitHub cron is not real-time, it may run with some delay)
  workflow_dispatch:       # also allow manual trigger

env:
  TRIGGER_URL: ${{secrets.CRON_JOB_URL}}  # your input URL
  BIN_NAME: trigger.bin
  BIN_PATH: trigger-bin/trigger

jobs:
  trigger-job:
    runs-on: ubuntu-latest

    steps:
      - name: Create binary folder
        run: mkdir -p trigger-bin

      - name: Check if trigger binary exists
        id: check_bin
        run: |
          if [[ -f "${{ env.BIN_PATH }}" ]]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Download trigger binary from private release if missing
        if: steps.check_bin.outputs.exists == 'false'
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          echo "Downloading trigger binary from GitHub release..."
          LATEST_TAG=$(curl -s -H "Authorization: token $GH_TOKEN" https://api.github.com/repos/vikshrogit/trigger/releases/latest | jq -r .tag_name)
          echo "$LATEST_TAG"
          ASSET_ID=$(curl -s -H "Authorization: token $GH_PAT" \
            https://api.github.com/repos/vikshrogit/trigger/releases/tags/$LATEST_TAG \
            | jq ".assets[] | select(.name == \"${{ env.BIN_NAME }}\") | .id")

          if [ -z "$ASSET_ID" ]; then
            echo "❌ Error: Asset '${{ env.BIN_NAME }}' not found in release $TAG"
            exit 1
          fi

            # ---- DOWNLOAD ----
           echo "⬇️ Downloading asset ID: $ASSET_ID ${{ env.BIN_NAME }}"
           curl -L \
            -H "Authorization: token $GH_PAT" \
            -H "Accept: application/octet-stream" \
            https://api.github.com/repos/vikshrogit/trigger/releases/assets/$ASSET_ID \
            -o "${{ env.BIN_PATH }}"
           ls trigger-bin
          cat ${{ env.BIN_PATH }}

      - name: Run trigger binary with URL
        run: |
          ${{ env.BIN_PATH }} -u "${{ env.TRIGGER_URL }}"
