name: Run Health Check

on:
  schedule:
    - cron: '* * * * *'  # Every minute
  workflow_dispatch:      # Optional manual trigger for testing

jobs:
  health-check:
    runs-on: ubuntu-latest
    environment: dev   
    steps:
      - name: Trigger Dev Cronjob URL
        env:
          CRON_URL: ${{ secrets.CRON_JOB_URL }}
        run: |
          echo "Triggering $CRON_URL"
          curl -s -o /dev/null -w "%{http_code}\n" "$CRON_URL"
